apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
  labels:
    test: value
  annotations:
    test: value
    test2: value
spec:
  replicas: 1
  revisionHistoryLimit: 10
  #revisionHistorylmt: 10
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: node-role.kubernetes.io/worker
      #               operator: In
      #               values:
      #                 - ''
      #             - key: kubernetes.io/os
      #               operator: In
      #               values:
      #                 - 'linux'
      containers:
      - name: basic-app
        image: busybox:latest # A simple image for demonstration
        command: ["sh", "-c", "echo $APP_MESSAGE && echo 'Application running on port:' $APP_PORT && sleep 3600"]
        env:
        - name: TEST_VAR
          value: value
        - name: TEST_VAR2
          value: value2
        envFrom:
        - configMapRef:
            name: basic-app-config
