apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: hook-tls
  name: deployment-replicas-webhook
  namespace: mutating-test
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: deployment-replicas-webhook
